
"""add_issue_harvest_project_farm_id

Revision ID: 0f62da97919e
Revises: b6f3ee86a31c
Create Date: 2026-09-23 19:36:20.571725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f62da97919e'
down_revision = 'b6f3ee86a31c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prototypes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('crop_name', sa.String(), nullable=False),
    sa.Column('total_duration_days', sa.Integer(), nullable=False),
    sa.Column('project_type', sa.String(), nullable=False),
    sa.Column('water_schedule_days', sa.Integer(), nullable=True),
    sa.Column('fertilizer_schedule_days', sa.Integer(), nullable=True),
    sa.Column('ao_visit_schedule_days', sa.Integer(), nullable=True),
    sa.Column('harvest_day', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_ao_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_ao_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prototypes_id'), 'prototypes', ['id'], unique=False)
    op.create_table('harvests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('farm_id', sa.String(), nullable=True),
    sa.Column('crop_cycle_id', sa.String(), nullable=True),
    sa.Column('work_order_id', sa.String(), nullable=True),
    sa.Column('crop_name', sa.String(), nullable=True),
    sa.Column('harvest_date', sa.Date(), nullable=True),
    sa.Column('yield_quantity', sa.Float(), nullable=True),
    sa.Column('yield_unit', sa.String(), nullable=True),
    sa.Column('market_price_per_unit', sa.Float(), nullable=True),
    sa.Column('gross_revenue', sa.Float(), nullable=True),
    sa.Column('harvesting_cost', sa.Float(), nullable=True),
    sa.Column('transport_cost', sa.Float(), nullable=True),
    sa.Column('other_expenses', sa.Float(), nullable=True),
    sa.Column('net_profit', sa.Float(), nullable=True),
    sa.Column('landowner_share_pct', sa.Float(), nullable=True),
    sa.Column('landowner_settlement_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'in_progress', 'completed', 'cancelled', name='harveststatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('proof_photos', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_harvests_id'), 'harvests', ['id'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('farm_id', sa.String(), nullable=True),
    sa.Column('work_order_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('reported_by', sa.String(), nullable=False),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='issueseverity'), nullable=False),
    sa.Column('status', sa.Enum('open', 'under_review', 'escalated', 'resolved', 'closed', name='issuestatus'), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('photo_urls', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_id'), 'issues', ['id'], unique=False)

    # Create enum types before using them (checkfirst=True avoids error if already exists)
    investmentverificationstage_type = sa.Enum('showed_interest', 'employee_contacted', 'customer_approved', 'site_visit', 'agreemented', 'zone_approved', 'founder_approved', 'payment_gateway', 'completed', name='investmentverificationstage')
    investmentverificationstage_type.create(op.get_bind(), checkfirst=True)
    projectapprovalstatus_type = sa.Enum('pending_approval', 'approved', 'rejected', name='projectapprovalstatus')
    projectapprovalstatus_type.create(op.get_bind(), checkfirst=True)

    op.add_column('investments', sa.Column('proposed_amount', sa.Float(), nullable=True))
    op.add_column('investments', sa.Column('questions', sa.Text(), nullable=True))
    op.add_column('investments', sa.Column('acknowledgement_accepted', sa.Boolean(), nullable=True))
    op.add_column('investments', sa.Column('verification_stage', sa.Enum('showed_interest', 'employee_contacted', 'customer_approved', 'site_visit', 'agreemented', 'zone_approved', 'founder_approved', 'payment_gateway', 'completed', name='investmentverificationstage'), nullable=True, server_default='showed_interest'))

    op.add_column('land_sales', sa.Column('is_broadcasted', sa.Boolean(), nullable=True))
    op.add_column('land_sales', sa.Column('broadcasted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('land_sales', sa.Column('broadcast_recipients_count', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('assigned_ao_id', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('qualification_data', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('need_analysis_data', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('value_prop_data', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('land_verification_data', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('ao_feasibility_data', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('commercial_model_data', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('proposal_data', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('negotiation_data', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('agreement_url', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('ao_quotation_doc', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('is_reviewed_by_employee', sa.Boolean(), nullable=True))
    op.add_column('leads', sa.Column('sent_to_client', sa.Boolean(), nullable=True))
    op.add_column('leads', sa.Column('approval_status', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('services_needed', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('price_to_complete', sa.Float(), nullable=True))
    op.add_column('leads', sa.Column('discount_amount', sa.Float(), nullable=True))
    op.add_column('leads', sa.Column('final_amount', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'leads', 'users', ['assigned_ao_id'], ['id'])
    op.add_column('projects', sa.Column('lead_id', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('farm_id', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('customer_id', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('approval_status', sa.Enum('pending_approval', 'approved', 'rejected', name='projectapprovalstatus'), nullable=True, server_default='approved'))

    op.add_column('projects', sa.Column('commercial_model_type', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('fixed_lease_amount', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('revenue_share_percentage', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('settlement_base', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('total_expenses', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('landowner_settlement', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('net_profit', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'projects', 'leads', ['lead_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'users', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'farms', ['farm_id'], ['id'])
    op.add_column('work_orders', sa.Column('project_id', sa.String(), nullable=True))
    op.add_column('work_orders', sa.Column('is_schedule_change_requested', sa.Boolean(), nullable=True))
    op.add_column('work_orders', sa.Column('schedule_change_reason', sa.Text(), nullable=True))
    op.add_column('work_orders', sa.Column('proposed_date', sa.Date(), nullable=True))
    op.add_column('work_orders', sa.Column('schedule_change_approval_status', sa.String(), nullable=True))
    op.add_column('work_orders', sa.Column('proof_urls', sa.Text(), nullable=True))
    op.add_column('work_orders', sa.Column('proof_submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('work_orders', sa.Column('is_verified_by_employee', sa.Boolean(), nullable=True))
    op.add_column('work_orders', sa.Column('is_accepted_by_customer', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'work_orders', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_orders', type_='foreignkey')
    op.drop_column('work_orders', 'is_accepted_by_customer')
    op.drop_column('work_orders', 'is_verified_by_employee')
    op.drop_column('work_orders', 'proof_submitted_at')
    op.drop_column('work_orders', 'proof_urls')
    op.drop_column('work_orders', 'schedule_change_approval_status')
    op.drop_column('work_orders', 'proposed_date')
    op.drop_column('work_orders', 'schedule_change_reason')
    op.drop_column('work_orders', 'is_schedule_change_requested')
    op.drop_column('work_orders', 'project_id')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'net_profit')
    op.drop_column('projects', 'landowner_settlement')
    op.drop_column('projects', 'total_expenses')
    op.drop_column('projects', 'settlement_base')
    op.drop_column('projects', 'revenue_share_percentage')
    op.drop_column('projects', 'fixed_lease_amount')
    op.drop_column('projects', 'commercial_model_type')
    op.drop_column('projects', 'approval_status')
    op.drop_column('projects', 'customer_id')
    op.drop_column('projects', 'farm_id')
    op.drop_column('projects', 'lead_id')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_column('leads', 'final_amount')
    op.drop_column('leads', 'discount_amount')
    op.drop_column('leads', 'price_to_complete')
    op.drop_column('leads', 'services_needed')
    op.drop_column('leads', 'approval_status')
    op.drop_column('leads', 'sent_to_client')
    op.drop_column('leads', 'is_reviewed_by_employee')
    op.drop_column('leads', 'ao_quotation_doc')
    op.drop_column('leads', 'agreement_url')
    op.drop_column('leads', 'negotiation_data')
    op.drop_column('leads', 'proposal_data')
    op.drop_column('leads', 'commercial_model_data')
    op.drop_column('leads', 'ao_feasibility_data')
    op.drop_column('leads', 'land_verification_data')
    op.drop_column('leads', 'value_prop_data')
    op.drop_column('leads', 'need_analysis_data')
    op.drop_column('leads', 'qualification_data')
    op.drop_column('leads', 'assigned_ao_id')
    op.drop_column('land_sales', 'broadcast_recipients_count')
    op.drop_column('land_sales', 'broadcasted_at')
    op.drop_column('land_sales', 'is_broadcasted')
    op.drop_column('investments', 'verification_stage')
    op.drop_column('investments', 'acknowledgement_accepted')
    op.drop_column('investments', 'questions')
    op.drop_column('investments', 'proposed_amount')
    op.drop_index(op.f('ix_issues_id'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_harvests_id'), table_name='harvests')
    op.drop_table('harvests')
    op.drop_index(op.f('ix_prototypes_id'), table_name='prototypes')
    op.drop_table('prototypes')
    # ### end Alembic commands ###
